version: '3.8'
services:
  turbo_octo_palm_tree_medicial_cards:
    container_name: turbo_octo_palm_tree_medicial_cards
    image: turbo_octo_palm_tree_medicial_cards
    ports:
      - "8000:8000"
    networks:
      - octo-palm-tree
    healthcheck:
      test: curl localhost:8000/ping
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  pg_database:
    container_name: pg_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: dev
    volumes:
      - /docker/volumes/turbo-octo-palm-tree/medicial-cards/database/pg_database
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dev"] 
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - octo-palm-tree

networks:
  octo-palm-tree: