on:
  push:
  pull_request:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Ruff
        run: |
          pip install ruff
          ruff check ./src
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          docker build . -t turbo_octo_palm_tree_medicial_cards
          docker compose up -d
          pip install pytest
          pytest tests
      
